default: &default
  adapter: postgresql
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: localhost

development:
  <<: *default
  database: changeons-dev
  host: 127.0.0.1

test:
  <<: *default
  database: changeons-test

production:
  <<: *default
  database: changeons-prod
