defaults: &defaults
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  twitter_access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
  twitter_access_secret: <%= ENV["TWITTER_ACCESS_SECRET"] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

staging:
  <<: *defaults